package latihan1;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Formulir extends javax.swing.JFrame {

    /**
     * Creates new form Formulir
     */
    public Formulir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        Kelas = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        proses = new javax.swing.JButton();
        Nama2 = new javax.swing.JLabel();
        Kelas2 = new javax.swing.JLabel();
        Alamat2 = new javax.swing.JLabel();
        nama1 = new javax.swing.JTextField();
        kelas1 = new javax.swing.JTextField();
        alamat1 = new javax.swing.JTextField();
        nama2 = new javax.swing.JTextField();
        kelas2 = new javax.swing.JTextField();
        alamat2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Formulir");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(164, 10, 60, 14);

        nama.setText("Nama");
        getContentPane().add(nama);
        nama.setBounds(40, 50, 27, 14);

        Kelas.setText("Kelas");
        getContentPane().add(Kelas);
        Kelas.setBounds(40, 90, 25, 14);

        alamat.setText("Alamat");
        getContentPane().add(alamat);
        alamat.setBounds(40, 130, 33, 14);

        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses);
        proses.setBounds(170, 160, 65, 23);

        Nama2.setText("Nama");
        getContentPane().add(Nama2);
        Nama2.setBounds(40, 200, 27, 14);

        Kelas2.setText("Kelas");
        getContentPane().add(Kelas2);
        Kelas2.setBounds(40, 240, 25, 14);

        Alamat2.setText("Alamat");
        getContentPane().add(Alamat2);
        Alamat2.setBounds(40, 280, 33, 14);

        nama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama1ActionPerformed(evt);
            }
        });
        getContentPane().add(nama1);
        nama1.setBounds(120, 50, 210, 20);
        getContentPane().add(kelas1);
        kelas1.setBounds(120, 90, 210, 20);

        alamat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamat1ActionPerformed(evt);
            }
        });
        getContentPane().add(alamat1);
        alamat1.setBounds(120, 130, 210, 20);
        getContentPane().add(nama2);
        nama2.setBounds(120, 200, 210, 20);
        getContentPane().add(kelas2);
        kelas2.setBounds(120, 240, 210, 20);

        alamat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamat2ActionPerformed(evt);
            }
        });
        getContentPane().add(alamat2);
        alamat2.setBounds(120, 280, 210, 20);

        setBounds(0, 0, 416, 415);
    }// </editor-fold>//GEN-END:initComponents

    private void nama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama1ActionPerformed

    private void alamat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamat2ActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        // TODO add your handling code here:
        String nama = nama1.getText();
        nama2.setText(nama);
        String kelas = kelas1.getText();
        kelas2.setText(kelas);
        String alamat = alamat1.getText();
        alamat2.setText(alamat);
    }//GEN-LAST:event_prosesActionPerformed

    private void alamat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamat1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat2;
    private javax.swing.JLabel Kelas;
    private javax.swing.JLabel Kelas2;
    private javax.swing.JLabel Nama2;
    private javax.swing.JLabel alamat;
    private javax.swing.JTextField alamat1;
    private javax.swing.JTextField alamat2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField kelas1;
    private javax.swing.JTextField kelas2;
    private javax.swing.JLabel nama;
    private javax.swing.JTextField nama1;
    private javax.swing.JTextField nama2;
    private javax.swing.JButton proses;
    // End of variables declaration//GEN-END:variables
}
