/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan4;

/**
 *
 * @author ASUS
 */
public class latiahn4 extends javax.swing.JFrame {

    /**
     * Creates new form latiahn4
     */
    public latiahn4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textfieldNama = new javax.swing.JTextField();
        textfieldAbsen = new javax.swing.JTextField();
        radiobuttonrpl = new javax.swing.JRadioButton();
        radiobuttontkj = new javax.swing.JRadioButton();
        radiobuttonProgamming = new javax.swing.JRadioButton();
        radiobuttonteknisi = new javax.swing.JRadioButton();
        radiobuttonAnimator = new javax.swing.JRadioButton();
        radiobuttonDesigner = new javax.swing.JRadioButton();
        buttonsubmit = new javax.swing.JButton();
        buttonhapus = new javax.swing.JButton();
        BUTTONEXIT = new javax.swing.JButton();
        textfieldhasil = new javax.swing.JTextField();
        labelNama = new javax.swing.JLabel();
        labelAbsen = new javax.swing.JLabel();
        labelJurusan = new javax.swing.JLabel();
        labelHOBI = new javax.swing.JLabel();
        labelHasil = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 51));
        getContentPane().setLayout(null);

        textfieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNamaActionPerformed(evt);
            }
        });
        getContentPane().add(textfieldNama);
        textfieldNama.setBounds(100, 100, 180, 30);
        getContentPane().add(textfieldAbsen);
        textfieldAbsen.setBounds(100, 140, 180, 30);

        radiobuttonrpl.setText("RPL");
        getContentPane().add(radiobuttonrpl);
        radiobuttonrpl.setBounds(100, 190, 43, 23);

        radiobuttontkj.setText("TKJ");
        radiobuttontkj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobuttontkjActionPerformed(evt);
            }
        });
        getContentPane().add(radiobuttontkj);
        radiobuttontkj.setBounds(190, 190, 43, 23);

        radiobuttonProgamming.setText("Progamming");
        getContentPane().add(radiobuttonProgamming);
        radiobuttonProgamming.setBounds(100, 220, 83, 23);

        radiobuttonteknisi.setText("Teknisi");
        getContentPane().add(radiobuttonteknisi);
        radiobuttonteknisi.setBounds(190, 220, 57, 23);

        radiobuttonAnimator.setText("Animator");
        getContentPane().add(radiobuttonAnimator);
        radiobuttonAnimator.setBounds(100, 250, 69, 23);

        radiobuttonDesigner.setText("Designer");
        radiobuttonDesigner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobuttonDesignerActionPerformed(evt);
            }
        });
        getContentPane().add(radiobuttonDesigner);
        radiobuttonDesigner.setBounds(190, 250, 67, 23);

        buttonsubmit.setText("Submit");
        buttonsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(buttonsubmit);
        buttonsubmit.setBounds(50, 280, 65, 23);

        buttonhapus.setText("Hapus");
        buttonhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonhapusActionPerformed(evt);
            }
        });
        getContentPane().add(buttonhapus);
        buttonhapus.setBounds(140, 280, 63, 23);

        BUTTONEXIT.setText("EXIT");
        BUTTONEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONEXITActionPerformed(evt);
            }
        });
        getContentPane().add(BUTTONEXIT);
        BUTTONEXIT.setBounds(230, 280, 55, 23);
        getContentPane().add(textfieldhasil);
        textfieldhasil.setBounds(10, 350, 380, 130);

        labelNama.setText("Nama");
        getContentPane().add(labelNama);
        labelNama.setBounds(10, 110, 27, 14);

        labelAbsen.setText("Absen");
        getContentPane().add(labelAbsen);
        labelAbsen.setBounds(10, 150, 30, 14);

        labelJurusan.setText("Jurusan");
        getContentPane().add(labelJurusan);
        labelJurusan.setBounds(10, 190, 60, 14);

        labelHOBI.setText("Hobi");
        getContentPane().add(labelHOBI);
        labelHOBI.setBounds(10, 230, 21, 14);

        labelHasil.setText("Hasil");
        getContentPane().add(labelHasil);
        labelHasil.setBounds(10, 310, 22, 14);

        jLabel1.setText("Biodata Siswa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 20, 100, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNamaActionPerformed

    private void radiobuttonDesignerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobuttonDesignerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobuttonDesignerActionPerformed

    private void BUTTONEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONEXITActionPerformed
        // TODO add your handling code here:
        dispose();
        textfieldhasil.setText(" ");
        labelNama.setText(" ");
        labelAbsen.setText(" ");
    }//GEN-LAST:event_BUTTONEXITActionPerformed

    private void radiobuttontkjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobuttontkjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobuttontkjActionPerformed

    private void buttonsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsubmitActionPerformed
        // TODO add your handling code here:
        String nama = textfieldNama.getText();
        String absen = textfieldAbsen.getText();
        String jurusan;
        String hobi = " ";
        //untuk rd
        if (radiobuttonrpl.isSelected())
            jurusan ="RPL";
        else if (radiobuttontkj.isSelected())
            jurusan ="TKJ";
        else
            jurusan =" ";
        //untuk checkbox
        if (radiobuttonProgamming.isSelected())
            hobi +=radiobuttonProgamming.getText()+ ", ";
        if (radiobuttonteknisi.isSelected())
            hobi +=radiobuttonteknisi.getText()+", ";
        if ( radiobuttonAnimator.isSelected())
            hobi += radiobuttonAnimator.getText()+", ";
          if (  radiobuttonDesigner.isSelected())
            hobi +=  radiobuttonDesigner.getText()+", ";
          textfieldhasil.setText("Nama Siswa : "+nama+"\nAbsen Siswa : "+absen+
                  "\nJurusan Anda : "+jurusan+"\nHobi Anda : "+hobi);
          
    }//GEN-LAST:event_buttonsubmitActionPerformed

    private void buttonhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonhapusActionPerformed
        // TODO add your handling code here:
        textfieldhasil.setText(" ");
        textfieldNama.setText(" ");
        radiobuttonProgamming.setText(" ");
        radiobuttonteknisi.setText(" ");
        radiobuttonAnimator.setText(" ");
        radiobuttonDesigner.setText(" ");
    }//GEN-LAST:event_buttonhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latiahn4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latiahn4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latiahn4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latiahn4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latiahn4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTTONEXIT;
    private javax.swing.JButton buttonhapus;
    private javax.swing.JButton buttonsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAbsen;
    private javax.swing.JLabel labelHOBI;
    private javax.swing.JLabel labelHasil;
    private javax.swing.JLabel labelJurusan;
    private javax.swing.JLabel labelNama;
    private javax.swing.JRadioButton radiobuttonAnimator;
    private javax.swing.JRadioButton radiobuttonDesigner;
    private javax.swing.JRadioButton radiobuttonProgamming;
    private javax.swing.JRadioButton radiobuttonrpl;
    private javax.swing.JRadioButton radiobuttonteknisi;
    private javax.swing.JRadioButton radiobuttontkj;
    private javax.swing.JTextField textfieldAbsen;
    private javax.swing.JTextField textfieldNama;
    private javax.swing.JTextField textfieldhasil;
    // End of variables declaration//GEN-END:variables
}
